language: cpp

compiler:
  - clang
  - gcc


install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt532 
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt53base qt53tools qt53connectivity
  - source /opt/qt53/bin/qt53-env.sh
  - cmake --version
  - qmake -v
  - $CXX -v
  - echo "Installing qhttpserver"
  - git clone --depth=10 https://github.com/Nava2/qhttpserver.git ~/qhttpserver
  - pushd ~/qhttpserver
  - mkdir build && pushd ./build
  - cmake ..
  - sudo make -j2 all && sudo make install
  - ls /usr/local/share/QHttpServer
  - ls /usr/local/lib | grep qhttp
  - echo "Finished installing qhttpserver"
  - popd && popd
  - pwd

script:
  - mkdir build/ && cd build/
  - cmake -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:/usr/local" ..
  - make all
  - sudo make install

after_success:
  - ./bin/qhttpserver-test

notifications:
  recipients:
    - kevin.brightwell2@gmail.com
  email:
    on_success: change
    on_failure: always
os:
  - linux
  - osx

